### ISSUE TITLE
Allow users to define cluster-scoped BuildTemplates

### ISSUE THREAD

**Issue by ImJasonH** [knative/build#302]
Some cluster operators might want to provide and manage predefined build templates, available across all namespaces.

We should create a `ClusterBuildTemplate` resource type which is available cluster-wide.

### Questions
* If a user creates a `BuildTemplate` in their namespace with a conflicting name with an existing `ClusterBuildTemplate` should we allow that or reject it?
* If we allow it, a Build would have to specify `template.name: 'some-namespace/the-template'` to specify the namespaced template.
* If we disallow it, creating a new `ClusterBuildTemplate` would have to look for a conflicting name across all namespaces.

I'm not familiar enough with Kubernetes API `ClusterFoo` idioms to know which is more consistent, hoping for pointers from those with more experience.

**Comment by pivotal-nader-ziada** [comment]
I will work with the following assumptions:

 1.  We should reject a `BuildTemplate` with a conflicting name. 
 2. The create `ClusterBuildTemplate` also should check existing namespaces and give an error on conflict. 

This is more in line with the general pattern of Resources not allowed in both Cluster and Namespace scopes

**Comment by cppforlife** [comment]
wouldnt that be a racy check?

**Comment by cppforlife** [comment]
@pivotal-nader-ziada no idea, i was thinking there would be more established way of doing this in kubernetes apis.

i was just looking at how ClusterRole vs Role in kube rbac is referenced (https://kubernetes.io/docs/reference/access-authn-authz/rbac/). looks like they use `roleRef` that contains `kind` key which could be ClusterRole or Role. (though they also have apiGroup). 

may be adding `templateKind: ClusterBuildTemplate | BuildTemplate (default)` next to `template` (which currently specifies name) is better instead of trying to do name check trickery. alternatively can add `templateRef` that could be used mutually exclusively with `template` for more advanced cases?

**Comment by pivotal-nader-ziada** [comment]
@cppforlife Thanks, I like the idea of adding the `templateKind`

**Comment by pivotal-nader-ziada** [comment]
Agreed, working on adding a template kind field to the build type instead of checking existing names as per @cppforlife and @evankanderson suggestion
