### ISSUE TITLE
Releases are broken

### ISSUE THREAD

**Issue by adrcunha** [knative/build#326]
/area test-and-release
/kind bug
/assign @adrcunha

## Expected Behavior

Releases are green every day. :)

## Actual Behavior

Releases were broken since 8/28 due to https://github.com/knative/build/pull/318

The PR added a dependency on `docker`, which is currently not available under Prow.

## Steps to Reproduce the Problem

  1. Go to https://testgrid.knative.dev/knative-build#release
  2. See that the tests pass, but the release build fails since 8/28.

**Comment by ImJasonH** [comment]
/cc @pivotal-nader-ziada 

What do you recommend to build the common base image used by `git-init` and `creds-init` during the release? We could manually release that image on-demand, but that seems like it would eventually get forgotten.

**Comment by pivotal-nader-ziada** [comment]
@ImJasonH Ideally we have a Prow job listening to changes in the `Dockerfile` or alpine base image and then upload a new image based on that? another option is to have a Prow job run periodically to update that

**Comment by shashwathi** [comment]
I think we need to consider non-Prow solution if docker cannot be installed on that.

**Comment by pivotal-nader-ziada** [comment]
@ImJasonH we can also switch to a base image in gcr.io public images `https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/ubuntu-slim@sha256:1d5c0118358fc7651388805e404fe491a80f489bf0e7c5f8ae4156250d6ec7d8/details?tab=info` 
but this will require changes to the Dockerfile to make it use apt-get instead of apk add

**Comment by pivotal-nader-ziada** [comment]
Or upload alpine base image to gcr.io

**Comment by adrcunha** [comment]
https://github.com/knative/test-infra/pull/102 properly enables docker in the Prow job and fixes the issue, there will be no need to do anything more complicated. :)

**Comment by adrcunha** [comment]
As a consequence, a new knative/build release is available :D

https://prow.knative.dev/log?job=ci-knative-build-release&id=1037441089818071040

**Comment by ImJasonH** [comment]
It looks like we have a different breakage now: https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-build-release/1037781079999647744/

I see:
- logs indicating Istio is being installed, which shouldn't be necessary to test knative/build
- `go test -v -tags=e2e -count=1 ./test/conformance --tag minikube` which isn't a path that exists in this repo

I'm not sure what's happening, it looks like it's running serving's release.sh in the knative/build repo, instead of [our release.sh](https://github.com/knative/build/blob/master/hack/release.sh)?

**Comment by adrcunha** [comment]
Ignore that, it was a manual run I started to test stuff. Real automatic releases are triggered at 1 AM.
