### ISSUE TITLE
Missing build object gc ?

### ISSUE THREAD

**Issue by zrss** [knative/build#342]
/area monitoring
/area test-and-release

/kind dev

## Expected Behavior

build controller handle the delete event from build informer, and do somthing like that in the case of build timeout

https://github.com/knative/build/blob/846036c8b91df25fa57da4d48a8ae5f9129c81f0/pkg/controller/build/controller.go#L286-L289

## Actual Behavior

https://github.com/knative/build/blob/846036c8b91df25fa57da4d48a8ae5f9129c81f0/pkg/controller/build/controller.go#L135-L140

lack of `DeleteFunc` handler impl

**Comment by shashwathi** [comment]
`DeleteFunc` is triggered when build object is deleted(AFAIK). How does implementing `Deletefunc` address timedout build GC? 

If build is timedout I do not think we want to delete the build itself. It is valuable to hold onto the build status because it contains information of failure. 

The only use case I could think of cleaning up builds is when user has piled up too many objects over time and want to cleanup. For this use case I could see an operator configuring like a month(or more) after which builds are automatically updated. Are you thinking of this use case ? or am I misunderstanding this altogether.

**Comment by zrss** [comment]
thanks for reply @shashwathi , no, i miss something ... the pod of build will set the `ownerReferences`

https://github.com/knative/build/blob/846036c8b91df25fa57da4d48a8ae5f9129c81f0/pkg/builder/cluster/convert/convert.go#L352-L359

and if the build resource is deleted by user, gcController (in kube-controller) will delete the pod belongs to it

> // List of objects depended by this object. If ALL objects in the list have
> // been deleted, this object will be garbage collected.
> OwnerReferences []OwnerReference

currently, `DeleteFunc` is useless in my opinion ...
