### ISSUE TITLE
Build e2e cannot run twice on an existing cluster

### ISSUE THREAD

**Issue by mattmoor** [knative/build#350]
I see:
```
--- FAIL: TestSimpleBuild (0.09s)
    simple_test.go:93: Error creating build: builds.build.knative.dev "simple-build" already exists
```

I think we just want to delete the `build-tests` namespace in a trap within `./test/e2e-test.sh`?

**Comment by mattmoor** [comment]
Interesting, I think we delete things in some cases?

**Comment by ImJasonH** [comment]
We should be attempting to delete the namespace at the end of the tests, and creating the namespace (ignoring already-exists errors) at the beginning of the tests.

Maybe we should also always delete the namespace at the beginning of the tests, in case the previous run didn't finish correctly?

**Comment by shashwathi** [comment]
I think we should also invoke `CleanupOnInterrupt` function to delete namespace on interrupt signals. 
Ref: https://github.com/knative/pkg/blob/master/test/cleanup.go

Another thing I have noticed is when I am running test back-to-back, deletion of builds take a while(due to couple of negative test cases) and consecutive e2e test run throws  `build-something already exists` error. 
I think we have to consider both @ImJasonH's idea to cleanup in beginning of tests along with @pivotal-nader-ziada's idea to teardown test setup at the end of tests.
